version: '3.1'

services:

  mysql:
    container_name: employee-registration-mysql
    image: mysql:8.3.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "3306:3306"

  rabbitmq:
    container_name: employee-registration-rabbitmq
    image: rabbitmq:3.12-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    container_name: employee-registration-api
    build: .
    image: employee-registration-api:latest
    restart: always
    depends_on:
      - mysql
      - rabbitmq
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: employee-registration-mysql
      MYSQL_PORT: 3306
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 123
      MYSQL_SCHEMA: employee_registration
      RABBITMQ_HOST: employee-registration-rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
