version: '3.1'

services:

  mysql:
    container_name: employee-registration-mysql
    image: mysql:8.3.0
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d/
    networks:
      - employee-registration-network
    environment:
      MYSQL_ROOT_PASSWORD: 123

  rabbitmq:
    container_name: employee-registration-rabbitmq
    image: rabbitmq:3.12-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - employee-registration-network

  api:
    container_name: employee-registration-api
    image: employee-registration-api:latest
    build: .
    restart: always
    depends_on:
      - mysql
      - rabbitmq
    ports:
      - "8080:8080"
    networks:
      - employee-registration-network
    environment:
      MYSQL_HOST: employee-registration-mysql
      MYSQL_PORT: 3306
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 123
      MYSQL_SCHEMA: employee_registration
      RABBITMQ_HOST: employee-registration-rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      SMTP_HOST=CHANGE: CHANGE
      SMTP_PORT=CHANGE: CHANGE
      SMTP_USERNAME=CHANGE: CHANGE
      SMTP_PASSWORD=CHANGE: CHANGE
      SMTP_FROM=CHANGE: CHANGE

networks:
  employee-registration-network:
    driver: bridge
