apiVersion: v1
kind: Service
metadata:
  name: employee-registration-rabbitmq-load-balancer
  labels:
    app: employee-registration-rabbitmq-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: employee-registration-rabbitmq
  ports:
    - name: "admin"
      protocol: TCP
      port: 15672
      targetPort: 15672
    - name: "service"
      protocol: TCP
      port: 5672
      targetPort: 5672