apiVersion: v1
kind: Pod
metadata:
  name: employee-registration-rabbitmq
  labels:
    app: employee-registration-rabbitmq
spec:
  containers:
    - name: employee-registration-rabbitmq
      image: rabbitmq:3.12-management
      ports:
        - containerPort: 5672
        - containerPort: 15672
