apiVersion: v1
kind: Service
metadata:
  name: employee-registration-rabbitmq-service
spec:
  type: ClusterIP
  selector:
    app: employee-registration-rabbitmq
  ports:
    - port: 5672
      targetPort: 5672
