apiVersion: v1
kind: Service
metadata:
  name: employee-registration-mysql-load-balancer
  labels:
    app: employee-registration-mysql-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: employee-registration-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306