apiVersion: v1
kind: Pod
metadata:
  name: employee-registration-mysql
  labels:
    app: employee-registration-mysql
spec:
  containers:
    - name: employee-registration-mysql
      image: mysql:8.3.0
      ports:
        - containerPort: 3306
      volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d/
          name: migration
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: employee-registration-mysql
              key: password
  volumes:
    - name: migration
      configMap:
        name: mysql-migration
