apiVersion: v1
kind: Service
metadata:
  name: employee-registration-mysql-service
spec:
  type: ClusterIP
  selector:
    app: employee-registration-mysql
  ports:
    - port: 3306
      targetPort: 3306
