apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-registration-api-deployment
  labels:
    app: employee-registration-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employee-registration-api
  template:
    metadata:
      labels:
        app: employee-registration-api
    spec:
      containers:
        - name: employee-registration-api
          image: gabrielgarciasp/employee-registration-api:latest
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_HOST
              value: "employee-registration-mysql-service"
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: employee-registration-mysql
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: employee-registration-mysql
                  key: password
            - name: MYSQL_SCHEMA
              value: "employee_registration"
            - name: RABBITMQ_HOST
              value: "employee-registration-rabbitmq-service"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: employee-registration-rabbitmq
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: employee-registration-rabbitmq
                  key: password
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 2
